name: Custom Issue Template
description: Provide details about your submission

body:
      
  - type: dropdown
    id: team-name
    attributes:
      label: Name of the Team
      description: Select the name of your team from the dropdown.
      options:
        - Team 1
        - Team 2
        - Team 3
        - Team 4
        - Team 5
        - Team 6
        - Team 7
        - Team 8
        - Team 9
        - Team 10
        - Team 11
        - Team 12
        - Team 13
        # Add more team names as needed
    validations:
      required: true

  - type: dropdown
    id: topic-name
    attributes:
      label: Name of the Topic
      description: Select the name of your Topic from the dropdown.
      options:
        - ResumeVault
        - TimeKeeper
        - ContractHub
        - CretifyMe
        - Others
        # Add more team names as needed
    validations:
      required: true

  - type: input
    id: other-team-name
    attributes:
      label: If "Other", please specify the team name
      placeholder: "Enter team name here"
    validations:
      required: false

   - type: input
    id: website-link
    attributes:
      label: Website link
      description: Provide the link to your project.
      placeholder: "www.example.com"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of your submission.
      placeholder: "Describe your project here..."
    validations:
      required: true

  - type: input
    id: repo-link-1
    attributes:
      label: Repository Link 1
      description: Provide the first repository link (if any).
      placeholder: "https://github.com/user/repo1"
    validations:
      required: false

  - type: input
    id: repo-link-2
    attributes:
      label: Repository Link 2
      description: Provide the second repository link (if any).
      placeholder: "https://github.com/user/repo2"
    validations:
      required: false

  - type: input
    id: repo-link-3
    attributes:
      label: Repository Link 3
      description: Provide the third repository link (if any).
      placeholder: "https://github.com/user/repo3"
    validations:
      required: false

  - type: input
    id: presentation-link
    attributes:
      label: Presentation Link
      description: Provide the link to your presentation.
      placeholder: "https://example.com/presentation"
    validations:
      required: false

  - type: input
    id: video-link
    attributes:
      label: Video Link
      description: Provide the link to your video.
      placeholder: "https://youtube.com/watch?v=example"
    validations:
      required: false

